stage 9 get statistic
Skip314/LearnBot pull request #10
Opened 2024-06-11 17:17 UTC by Skip314

2024-06-17 13:33 UTC, danelyan requested changes

2024-06-17 13:33 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +            when (botService.getData()) {
не может быть одновременно text и data.
При отправке сообщения text, при нажатии на кнопку - data.

Должно быть несколько отдельных if блоков

2024-06-17 22:31 UTC, Skip314 commented on src/main/kotlin/Telegram.kt
> +            when (botService.getData()) {
В боте переход на вкладку изучения слов только со второго нажатия
Вывод после неверного выбора еще раз, а только потом ответ верно или нет

2024-06-17 22:35 UTC, Skip314 commented on src/main/kotlin/Telegram.kt
> +            when (botService.getData()) {
путаница с id ответа и когда все таки угадаешь 1 рвз, сразу все слова выучены

2024-06-19 10:08 UTC, danelyan approved these changes
Давай оставим так и перейдем к финалу.
После внедрения Kotlinx.Serialization дам подробные комментарии по текущей архитектуре.

2024-06-19 14:01 UTC, merged