stage 2 data class and quantityApprove
Skip314/LearnBot pull request #2
Opened 2024-04-09 09:10 UTC by Skip314

2024-04-09 12:26 UTC, danelyan requested changes

2024-04-09 12:26 UTC, danelyan commented on src/main/kotlin/Main.kt
> +    createStartWords()
В целом, будет гибче если мы будем считывать словарь из файла.
Это дает возможность менять словарь без пересборки приложения.
На крайний случай можно проверять, существует ли файл:
```Kotlin
if(!wordsFile.exist() {
    createStartWords()
}
```

2024-04-09 12:26 UTC, danelyan commented on src/main/kotlin/Main.kt
> +        val word = Words(original = line[0], translate = line[1], quantityApprove = line[2].toInt())
Тут можно сделать чуть устойчивее к ошибкам в файле:
```Kotlin
line.getOrNull(2)?.toIntOrNull() ?: 0
```

2024-04-09 12:26 UTC, danelyan commented on src/main/kotlin/Main.kt
> +fun createStartWords(){
не хватает пробела между `()` и `{`
Используй [автоформатирование](https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html)

2024-04-10 09:54 UTC, danelyan requested changes

2024-04-10 09:54 UTC, danelyan commented on src/main/kotlin/Main.kt
> +        line.getOrNull(2)?.toIntOrNull() ?: 0
эта строчка ничего не делает

2024-04-12 07:14 UTC, danelyan requested changes

2024-04-12 07:14 UTC, danelyan commented on src/main/kotlin/Main.kt
> +        val word = Words(original = line[0], translate = line[1], quantityApprove = line[2].toInt())
Давай сделаем вот так:
```Kotlin
val word = Words(original = line[0], translate = line[1], quantityApprove = line.getOrNull(2)?.toIntOrNull() ?: 0)
```
getOrNull - это получение 2 элемента из списка, или null - если элементов меньше
toIntOrNull - конвертация строки в число, или null - если конвертация невозможна (в строке не число)

2024-04-12 07:14 UTC, danelyan commented on src/main/kotlin/Main.kt
> +    val dictionaryWords: MutableMap<String, String> = mutableMapOf()
для чего тут Map?
Нам достаточно обычного списка

2024-04-12 07:14 UTC, danelyan commented on src/main/kotlin/Main.kt
> +        dictionaryWords[word.original] = word.translate
а тут просто добавляем в список новые слова

2024-04-12 07:14 UTC, danelyan commented on src/main/kotlin/Main.kt
> +        wordsFile.appendText("${word.original}|${word.translate}|${word.quantityApprove}\n")
это тут не нужно, сохранять словарь из списка обратно мы будем позже

2024-04-12 07:14 UTC, danelyan commented on src/main/kotlin/Main.kt
> +    if (wordsFile.exists()) createStartWords()
тут если перевести код в слова:
"если файл существует - создать еще один файл"
Нужно отрицание перед `wordsFile.exists()`, то есть - `!wordsFile.exists()`

2024-04-12 07:28 UTC, Skip314 commented on src/main/kotlin/Main.kt
> +    if (wordsFile.exists()) createStartWords()
если я так сделаю, в текстовом файле перестанут обновляться слова

2024-04-12 21:14 UTC, danelyan requested changes

2024-04-12 21:14 UTC, danelyan commented on src/main/kotlin/Main.kt
> +    if (wordsFile.exists()) createStartWords()
Сейчас мы делаем основу для нашего консольного тренажера слов, который будем в дальнейшем апгрейдить до Телеграм-бота.

На текущем этапе наша задача написать код, который грузит из файла словарь.
Словарь, в нашем случае, список Word'ов.
Логика такая - если файла нет, создаем его и заполняем словами.
Если есть - ничего не делаем, ведь словарь предоставлен извне. И возможно в этом словаре извне больше слов, чем мы заложили в коде в методе createStartWords().
Но на случай если файл не был поставлен вместе с нашим приложением, мы создаем его и заполняем.

Давай удалим выше строку:
```Kotlin
wordsFile.writeText("")
```
Она по сути затирает все содержимое словаря, и тогда мы вынуждены всегда заполнять словарь заново.

2024-04-12 21:14 UTC, danelyan commented on src/main/kotlin/Main.kt
> +    wordsFile.writeText("")
Эта строка тоже не нужна, она по сути затирает все слова в файле.

М будем этот файл редактировать на более поздних этапах, чтобы изменять значение количества правильных ответов для слова. Это поле в будущем мы будем использовать, чтобы определять выученные слова. Напомню по ТЗ - 3 раза правильно отвеченное слово считается выученным

2024-04-12 21:14 UTC, danelyan commented on src/main/kotlin/Main.kt
> +        wordsFile.appendText("${word.original}|${word.translate}|${word.quantityApprove}\n")
Повторюсь, это строка не нужна. По условию:

>  2. На каждой итерации прохода по строкам файла создавать объект типа Word и добавлять его в dictionary

Это есть 

> 3. Добавить информацию о количестве правильных ответов в файл `words.txt` и в сущность `Word`

Тоже сделали, добавив разделитель в файл words.txt и поле quantityApprove в data-класс.

> 4. Распечатать содержимое dictionary в консоль

А этого нет. 
 
Давай удалим `wordsFile.appendText("${word.original}|${word.translate}|${word.quantityApprove}\n")` и добавим после цикла заполнения словаря вывод содержимого в консоль

2024-04-16 07:36 UTC, Skip314 commented on src/main/kotlin/Main.kt
> +    wordsFile.writeText("")
Если не затирать слова, то при каждом включении программы она будет добавлять те же слова заново. А так даже новые слова сохранены перед этим в список и никуда они не денутся

2024-04-16 16:27 UTC, danelyan approved these changes

2024-04-16 19:47 UTC, merged