stage 4
Skip314/LearnBot pull request #5
Opened 2024-04-17 15:34 UTC by Skip314

2024-04-18 10:17 UTC, danelyan requested changes
Хорошо. Но не учитывается ситуация, когда остается одно невыученное слово.
Пользователю будет очевиден ответ.
Давай дополнять недостающими выученными словами

2024-04-18 10:17 UTC, danelyan commented on src/main/kotlin/Main.kt
> +import kotlin.random.Random
этот импорт не нужен

2024-04-18 10:17 UTC, danelyan commented on src/main/kotlin/Main.kt
> +        println()
Этот println не нужен

2024-04-18 10:17 UTC, danelyan commented on src/main/kotlin/Main.kt
> +        for (word in dictionaryWords) if (word.quantityApprove <= APPROVED_LEARN_WORDS) unlearnedWords.add(word)
тут можно объеденить в одно выражение:
```Kotlin
val unlearnedWords = dictionaryWords.filter { it.quantityApprove <= APPROVED_LEARN_WORDS }
```

2024-04-18 10:17 UTC, danelyan commented on src/main/kotlin/Main.kt
> +        if (unlearnedWords.size == 0) {
Тут можно использовать вызов метода сравнение с размером.
Кстати обращай внимания на рекомендации Idea:
<img width="400" alt="Screenshot 2024-04-18 at 14 05 40" src="https://github.com/Skip314/LearnBot/assets/7125622/0e9ffeff-8f54-4317-963b-423eb48d1d15">

Это не критично в большинстве случаев, просто добавляет лишнее сравнение.
Но можно представить себе кастомную реализацию List, у которой метод isEmpty() работает быстрее чем вычисление размера всей коллекции

2024-04-18 10:17 UTC, danelyan commented on src/main/kotlin/Main.kt
> +        val fourWords = unlearnedWords.take(4)
4 нужно вынести в константы

2024-04-18 10:17 UTC, danelyan commented on src/main/kotlin/Main.kt
> +        unlearnedWords.shuffle()
можно объеденить со строкой ниже: `unlearnedWords.shuffled().take()`

2024-04-18 10:17 UTC, danelyan commented on src/main/kotlin/Main.kt
> +            num++
компактнее использовать forEachIndexed { ... }

2024-04-19 09:42 UTC, Skip314 commented on src/main/kotlin/Main.kt
> +        unlearnedWords.shuffle()
Я пробовал тогда и сейчас, не дает использовать take вместе с фильтровкой

2024-04-19 09:42 UTC, Skip314 commented on src/main/kotlin/Main.kt
> +        unlearnedWords.shuffle()
вместе с перемешкой

2024-04-21 05:38 UTC, danelyan commented on src/main/kotlin/Main.kt
> +        unlearnedWords.shuffle()
обрати внимание на название метода, их два разных:
- shuffle
- shuffled
Первый работает только на мутабельных списках и перемешивает их элементы.
Второй создает новую коллекцию состоящую из перемешанных элементов первой

2024-04-21 07:48 UTC, danelyan requested changes

2024-04-21 07:48 UTC, danelyan commented on src/main/kotlin/Main.kt
> +        var learnWords = unlearnedWords.toMutableList().shuffled().take(QUANTITY_WORDS)
Отлично! вот тут еще давай уберем toMutableList() и можно вливать

2024-04-21 07:49 UTC, danelyan requested changes

2024-04-21 07:49 UTC, danelyan commented on src/main/kotlin/Main.kt
> +        learnWords.forEach { words ->
и вот тут попробуй forEachIndexed {}

2024-04-23 06:53 UTC, danelyan approved these changes

2024-04-23 10:48 UTC, merged