5
Skip314/LearnBot pull request #6
Opened 2024-04-26 13:37 UTC by Skip314

2024-04-26 15:16 UTC, danelyan requested changes
Приложение падает, если в меню ввести любой символ кроме цифры:
<img width="400" alt="Screenshot 2024-04-26 at 19 16 10" src="https://github.com/Skip314/LearnBot/assets/7125622/3c35df8a-3944-4070-ad0f-4cfb2b8e6c48">

2024-04-26 15:16 UTC, danelyan commented on src/main/kotlin/Main.kt
> +fun saveDictionary(approve: Words) {
Давай переименуем класс Words, все таки принято сущности называть в ед. числе

2024-04-26 15:16 UTC, danelyan commented on src/main/kotlin/Main.kt
> +    dictionaryWords[dictionaryWords.indexOf(approve)].quantityApprove += 1
тут можно approve.quantityApprove++
Однако в целом - метод у тебя называется saveDictionary(), почему внутри ты что-то инкрементируешь?

2024-04-26 15:20 UTC, danelyan requested changes

2024-04-26 15:20 UTC, danelyan commented on src/main/kotlin/Main.kt
> +        println("0 - выход в главное меню")
давай разместим в самом низу меню:
<img width="380" alt="Screenshot 2024-04-26 at 19 19 36" src="https://github.com/Skip314/LearnBot/assets/7125622/3477f607-3fc2-453f-a071-ac779f099f6f">

2024-04-27 20:31 UTC, Skip314 commented on src/main/kotlin/Main.kt
> +    dictionaryWords[dictionaryWords.indexOf(approve)].quantityApprove += 1
Не понял вопрос

2024-04-30 09:19 UTC, danelyan requested changes
Приложение падает, если в меню ввести любой символ кроме цифры:
<img width="400" alt="Screenshot 2024-04-26 at 19 16 10" src="https://github.com/Skip314/LearnBot/assets/7125622/3c35df8a-3944-4070-ad0f-4cfb2b8e6c48">

2024-04-30 09:19 UTC, danelyan commented on src/main/kotlin/Main.kt
> +    approve.quantityApprove += 1
Метод saveDictionary судя по названию просто сохраняет словарь.
Он не называется incrementWordAndSaveDictionary. 
Давай делать инкремент до вывоза saveDictionary и не передавать туда Word.

2024-05-22 18:53 UTC, danelyan requested changes
![Uploading Screenshot 2024-05-22 at 21.45.47.png…]()

- Запятые выглядят лишними в меню
- Можно не выводить массив слов при старте приложения

2024-05-22 18:53 UTC, danelyan commented on src/main/kotlin/Main.kt
> +            dictionaryWords[dictionaryWords.indexOf(approve)].quantityApprove += 1
Можно проще:
```Kotlin
approve.quantityApprove += 1
```

2024-05-23 15:08 UTC, danelyan approved these changes
Отлично! Идем дальше

2024-05-23 21:27 UTC, merged